### ISSUE TITLE
SAO: Infinity Moment

### ISSUE THREAD

**Issue by EnglishPatchFanatic** [Saramagrean/SAO-IM-HD-Remake-Project#1]
Firstly, this HD patch really does its job and I thank you for the hardwork youve done regarding this HD texture Patch very nice big pp!

The only thing hindering us to fully enjoy the experience is the full english patch, can you provide us with the link regarding the patch? It would really help us enjoy this game a lot, thank you so much for the time reading this.

**Comment by Saramagrean** [comment]
Soon. :)

**Comment by EnglishPatchFanatic** [comment]
> Soon. :)

You've been saying that for 2 years already... Haoi Truang.

**Comment by YulioChristian** [comment]
> > Soon. :)
> 
> You've been saying that for 2 years already... Haoi Truang.

its update now v2
but i dont know how to extract, it have 3 part, but in download section, just part 2 & 3

**Comment by YulioChristian** [comment]
> Soon. :)

how to extract this translate?
i mean,how to use this translate?

**Comment by EnglishPatchFanatic** [comment]
@Saramagrean you are one hell of a hero ya know that, just that where is the first part of the patch? Is it only 400mb?

**Comment by Saramagrean** [comment]
Still uploading...

**Comment by EnglishPatchFanatic** [comment]
> Still uploading, my internet is very poor...
We'll be waiting patiently! Thank you so much @Saramagrean

With your HD texture pack this game is gonna pack a punch on the ppsspp!

**Comment by MediaMaquina** [comment]
So.....any news on part 1 of the patch? Thanks.

**Comment by Saramagrean** [comment]
Done.

**Comment by MediaMaquina** [comment]
Thanks man you are legend!

**Comment by MediaMaquina** [comment]
Sorry but what's the expected iso to be applied to? I used clean Japanese

  CRC-32: d97acf65
     MD5: bcf29f8a7aa234c83fab6ab6aa842261
   SHA-1: 78da017a5c90e34101608e7ff187db0e02e22177

but it says invalid checksum, so what iso is the patch based on?

**Comment by Pwnzer2000** [comment]
It's got to be the PSN version. I got mine to finally patch.

**Comment by MediaMaquina** [comment]
Oh i forgot the PSN version existed. Thanks it worked.

**Comment by Saramagrean** [comment]
Thank you Hoaitrung-san for hardwork. :)
